services:
    menu.mega:
        class: WL\MaterializeTemplateBundle\Lib\Menu\MegaMenuBuilder
        arguments: [@repo.factory.cache.file, @categories.allowed]
    menu.dropDown:
        class: WL\MaterializeTemplateBundle\Lib\Menu\DropDownMenuBuilder
        arguments: [@repo.factory.cache.file]
