wl_homepage:
    path: /
    defaults: { _controller: WLAppBundle:Default:index }

category:
    path: /kategoria-{categoryUrlWithFilters}
    defaults: { _controller: WLAppBundle:Category:index }
    requirements:
        categoryUrlWithFilters: ".+"

product:
    path: /produkt-{productUrl}.html
    defaults: { _controller: WLAppBundle:Product:index }
    requirements:
        productUrl: ".+"

search:
    path: /produkty-{phrase}
    defaults: { _controller: WLAppBundle:Search:index }
    requirements:
        phrase: ".+"

map_categories:
    path: /mapa-kategorii
    defaults: { _controller: WLAppBundle:MapCategory:index }

rating_add:
    path: /daja_ocene
    defaults: { _controller: WLAppBundle:Product:addRate }
    methods:  [POST]

